### ISSUE TITLE
`FCM: NON-DROP FRAME` are missing from round-trip

### ISSUE THREAD

**Issue by lofidevops** [simonh10/python-edl#6]
Steps to reproduce:
- Read and then write an EDL file as follows:

```
with open("020_Test.edl") as read_file:
    test_edl = parser.parse(read_file)

    with open("outfile.edl", "w") as write_file:
        write_file.write(test_edl.to_string())
```

What should happen:
- Output file is near-identical to input

What happens instead:
- Most lines are near-identical (correct)
- `FCM: NON-DROP FRAME` lines are missing

[020_Test.edl.txt](https://github.com/simonh10/python-edl/files/87503/020_Test.edl.txt)
[outfile.edl.txt](https://github.com/simonh10/python-edl/files/87502/outfile.edl.txt)

**Comment by kwill** [comment]
This appears to be addressed by https://github.com/AdricEpic/python-edl/tree/cmx_conform
